# Site settings
title: BHL
logo: "/img/Network_512.png"
email: b.hintonlever@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Ben Hinton-Lever and I'm fascinated by all things that data & visualisations can tell us. 
baseurl: "/index.html" # the subpath of your site, e.g. /blog/
url: "http://hintonlever.github.io/" # the base hostname & protocol for your site
github_username:  hintonlever


# Build settings
markdown: kramdown
highlighter: pygments